library(readr)
library(FactoMineR)

df <- read.csv("data/reports.csv")
summary(df)
df$dataset <- as.factor(df$dataset)
df$tokenizer <- as.factor(df$tokenizer)
df$vectorizer <- as.factor(df$vectorizer)
df$classifier <- as.factor(df$classifier)
df$remove_diacritics <- as.factor(df$remove_diacritics)
df$remove_urls <- as.factor(df$remove_urls)
df$remove_symbols <- as.factor(df$remove_symbols)
df$split_sentences <- as.factor(df$split_sentences)
df$lower <- as.factor(df$lower)
df$lemmatize <- as.factor(df$lemmatize)
df$stemmatize <- as.factor(df$stemmatize)
